version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
    - 'postgres_data:/var/lib/postgresql/data/'
  redis:
    image: redis
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile.production
    image: victor755555/graphl-rails
    links:
    - postgres
    - redis
    depends_on:
    - postgres
    ports:
    - "8000:8000"
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@postgres/postgres
volumes:
  postgres_data:
    driver: local
